### ISSUE TITLE
memento-mori-string not displaying in frame title

### ISSUE THREAD

**Issue by doolio** [gvol/emacs-memento-mori#20]
I have set the following customizations:

`memento-mori-display-in-modeline` to `nil` and 
`memento-mori-display-in-frame-title` to `t`

I assumed the string would be appended or prepended to the existing frame title but instead it clobbers the existing title and nothing is shown though a tooltip suggests the frame title is "Untitled window".

![image](https://github.com/gvol/emacs-memento-mori/assets/13859009/950ec2db-5b4b-42f1-89ed-488b420ee8f4)

**Comment by gvol** [comment]
Hmm.  I tried it on my Mac and it worked there.  You do have to turn it on *before* turning on memento-mori-mode (or try toggling memento-mode).  I wonder if I can change that at least when set via customize...

What's the value of `frame-title-format`?

**Comment by doolio** [comment]
> or try toggling memento-mode

No, that did not work for me though `memento-mori-string` is a non empty string.

> What's the value of `frame-title-format`?

After toggling the mode:

```emacs-lisp
(memento-mori--frame-title-construct :eval
                                     (if
                                         (buffer-file-name)
                                         (abbreviate-file-name
                                          (buffer-file-name))
                                       "%b"))
```

**Comment by gvol** [comment]
Hopefully this should be fixed, but feel free to reopen if not.  I'm a little worried that format-spec has changed in newer versions or something.  I build Emacs from master periodically.

**Comment by doolio** [comment]
Still not working for me. Now `frame-title-format` is:

```emacs-lisp
(:eval
 (if
     (buffer-file-name)
     (abbreviate-file-name
      (buffer-file-name))
   "%b")
 memento-mori--frame-title-construct)
```

I presume for you, you had not already configured `frame-title-format`?

**Comment by gvol** [comment]
You're right.  I had a string for `frame-title-format`.  The problem is that you have a list, but it's really a single construct.  I wonder if it's always safe to just wrap it in another layer of list (seems to be in my very limited experimentation).  Or maybe it's best to just tell users how to add it manually?

**Comment by doolio** [comment]
If I manually set this variable as follows it displays as expected.

```emacs-lisp
((:eval
  (if
      (buffer-file-name)
      (abbreviate-file-name
       (buffer-file-name))
    "%b"))
 memento-mori--frame-title-construct)
```
Notice, I've wrapped the `:eval` sexp in parentheses.

(Aside, if I view this variable using `describe-variable` I see something like the above. However, if I look into my custom file it appears as follows:

```emacs-lisp
 '(frame-title-format
   '(:eval
     (if
         (buffer-file-name)
         (abbreviate-file-name
          (buffer-file-name))
       "%b")) t)
```

Not sure where the `t` symbol at the end comes from.)

**Comment by gvol** [comment]
The extra `t` is for `custom-set-variables`.  It's the `NOW` portion though to be honest, I'm not entirely sure it does.
